cup_cakes_homepage:
    path:     /Patisserie
    defaults: { _controller: CupCakesBundle:Default:index }
cup_cakes_Dashbord:
    path:    /Admin
    defaults: { _controller: CupCakesBundle:Default:Admin }
cup_cakes_Eshop:
    path:   /Client
    defaults: { _controller: CupCakesBundle:Default:client }
cup_cakes_Formateur:
    path:   /Formateur
    defaults: { _controller: CupCakesBundle:Default:Formateur }
cup_cakes_DashAdmin:
    path:   /DashAdmin
    defaults: { _controller: CupCakesBundle:Default:DashAd }
cup_cakes_commande:
    resource: "@CupCakesBundle/Resources/config/routing/Commande.yml"
    prefix:   /Commande
cup_cakes_produit:
    resource: "@CupCakesBundle/Resources/config/routing/Produit.yml"
    prefix:   /Produit
cup_cakes_recette:
    resource: "@CupCakesBundle/Resources/config/routing/Recette.yml"
    prefix:   /Recette