cup_cakes_homepage:
    path:     /Patisserie
    defaults: { _controller: CupCakesBundle:Default:index }
cup_cakes_Dashbord:
    path:    /Admin
    defaults: { _controller: CupCakesBundle:Default:Admin }
cup_cakes_Eshop:
    path:   /Client
    defaults: { _controller: CupCakesBundle:Default:client }
cup_cakes_Formateur:
    path:   /Formateur
    defaults: { _controller: CupCakesBundle:Default:Formateur }
cup_cakes_DashAdmin:
    path:   /DashAdmin
    defaults: { _controller: CupCakesBundle:Default:DashAd }
CommandeMain:
    path:     /Commande
    defaults: { _controller: CupCakesBundle:Commande:Main }
CommandeSuivie:
    path:     /SuivieCommande
    defaults: { _controller: CupCakesBundle:Commande:Suivie }
ProduitListe:
    path:     /ProduitListe
    defaults: { _controller: CupCakesBundle:Produit:Liste}
ProduitSeul:
    path:     /ProduitNom
    defaults: { _controller: CupCakesBundle:Produit:Proddet}