cup_cakes_homepage:
    path:     /Patisserie
    defaults: { _controller: CupCakesBundle:Default:index }
cup_cakes_Dashbord:
    path:    /Admin
    defaults: { _controller: CupCakesBundle:Default:Admin }
cup_cakes_Eshop:
    path:   /Client
    defaults: { _controller: CupCakesBundle:Default:client }
cup_cakes_client:
    resource: "@CupCakesBundle/Resources/config/routing1/Client.yml"
    prefix:   /Client
cup_cakes_Patisseurie:
    resource: "@CupCakesBundle/Resources/config/Routing1/Patisseurie.yml"
    prefix:   /Patisserie
cup_cakes_Formateur:
    resource: "@CupCakesBundle/Resources/config/Routing1/Formateur.yml"
    prefix:   /Formateur
