ValiderPanier:
    path:     /main/{total}
    defaults: { _controller: CupCakesBundle:Commande:ValiderPanier }
CommandeSuivie:
    path:     /suivie
    defaults: { _controller: CupCakesBundle:Commande:Suivie }
AfficherPanier:
    path:     /panier
    defaults: { _controller: CupCakesBundle:Commande:liste }
CommandeListePatisserie:
    path:     /ListeComm
    defaults: { _controller: CupCakesBundle:Commande:PatisserieListe }
ModificationEtat:
    path:     /ModificationEtat/{id}
    defaults: { _controller: CupCakesBundle:Commande:UpdateEtatLivraison }
PasserCommande:
    path:     /ajouter/{id}
    defaults: { _controller: CupCakesBundle:Commande:AjouterPanier }
SupprimerPanier:
    path:     /supprimer/{id}
    defaults: { _controller: CupCakesBundle:Commande:SupprimerPanier }
AjouterFeedback:
    path:     /Feedback/{id}
    defaults: { _controller: CupCakesBundle:FeedBack:AjouterFeedback }
ListeFeedback:
    path:     /Feedback
    defaults: { _controller: CupCakesBundle:FeedBack:ListeFeedback }
DetailFeedback:
    path:     /FeedbackDetail/{id}
    defaults: { _controller: CupCakesBundle:FeedBack:DetailFeedback }
AjouterLine:
    path:     /Finie
    defaults: { _controller: CupCakesBundle:Commande:AjouterLine }
Pdf:
    path:     /pdf/{id}
    defaults: { _controller: CupCakesBundle:Commande:PDFFacture }
AnnulationCmd:
    path:     /Supp/{id}
    defaults: { _controller: CupCakesBundle:Commande:SupprimerCmd }
recherche_user_commande:
    path:     /commandeRecherche
    defaults: { _controller: CupCakesBundle:Commande:Recherche }